name: Process Videos 2.0

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install ultralytics requests boto3 python-dotenv opencv-python

    - name: Install Backblaze B2 SDK
      run: pip install b2sdk


    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Run processor
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python process_video.py
